# Generated by Django 4.1.5 on 2023-04-12 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0005_alter_article_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="article_image",
            field=models.FileField(
                blank=True, null=True, upload_to="", verbose_name="Add an Article Image"
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment_author",
                    models.CharField(max_length=50, verbose_name="Name"),
                ),
                (
                    "comment_content",
                    models.CharField(max_length=200, verbose_name="Comment"),
                ),
                (
                    "comment_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date Commented"
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="article.article",
                        verbose_name="Article",
                    ),
                ),
            ],
        ),
    ]
