# Generated by Django 4.1.5 on 2023-04-12 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0006_alter_article_article_image_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article", options={"ordering": ["-created_date"]},
        ),
        migrations.AlterModelOptions(
            name="comment", options={"ordering": ["-comment_date"]},
        ),
    ]
